# Site settings
url: https://principles.design
title: Design Principles
description: A curated collection of design principles used as decision-making frameworks. Practical examples and guidance for teams building products.
twitter: "@dsgnprinciples"
twitter:
  username: dsgnprinciples
logo: /favicon.png

twitter:
  image: https://principles.design/favicon.png
facebook:
  image: https://principles.design/favicon.png
# Custom
twitter-url: https://twitter.com/dsgnprinciples
contribute-url: https://github.com/benbrignell/principles.design#contributing
gitter-url: https://gitter.im/design-principles

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
include: ['_pages']

# Current site environment
environment: production

collections:
    examples:
        output: true
        permalink: /examples/:name
    components:
        output: false
    writing:
        output: true
        permalink: /writing/:name

defaults:
  - scope:
      path: ""
      type: "examples"
    values:
      layout: "example"
  - scope:
      path: ""
      type: "writing"
    values:
      layout: "page"

exclude:
- node_modules
plugins:
- jekyll-seo-tag


liquid:
    error_mode: lax # because of featured loop on homepage throwing minor validation error
