# Site settings
url: "https://principles.design"
title: "Design Principles"
description: "An Open Source repository of Design Principles and methods"
twitter: "@dsgnprinciples"
twitter:
  username: dsgnprinciples

# Custom variables
twitter-url: "https://twitter.com/dsgnprinciples"
contribute-url: "https://github.com/benbrignell/principles.design#contributing"
gitter-url: "https://gitter.im/design-principles"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

collections:
    examples:
        output: true
        permalink: /examples/:name
    components:
        output: false
plugins:
- jekyll-last-modified-at # doesn't work with collections
- jekyll-seo-tag

liquid:
    error_mode: lax # because of featured loop on homepage throwing minor validation error
